const pj = require('../package.json')
module.exports = {
  name: 'kintone快速拷贝记录编号',
  namespace: pj.homepage,
  version: '0.0.1',
  description: pj.description,
  author: pj.author,
  copyright: pj.author,
  license: 'MIT',
  match: [
    'https://*.cybozu.cn/k/*',
    'https://*.cybozu.com/k/*',
    'https://*.cybozu-dev.com/k/*',
    'https://*.s.cybozu.cn/k/*',
    'https://*.s.cybozu.com/k/*',
    'https://*.s.cybozu-dev.com/k/*',
    'https://*.kintone.com/k/*',
  ],
  require: ['https://cdn.jsdelivr.net/npm/sweetalert2@11'],
  'run-at': 'document-end',
  supportURL: pj.bugs.url,
  homepage: pj.homepage,
  grant: ['GM_addStyle'],
  icon: 'https://img.icons8.com/material-outlined/256/code-file.png',
}
